apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: mpijob-${JOB_INDEX}
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  sshAuthMountPath: /home/mpiuser/.ssh
    #  mpiImplementation: Intel
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        metadata:
          labels:
            app: model
        spec:
          volumes:
          - name: my-pvc-nfs
            persistentVolumeClaim:
              claimName: nfs
          containers:
          - image: linusseelinger/model-exahype-tsunami:latest
            name: mpi-launcher
            volumeMounts:
              # name must match the volume name below
              - name: my-pvc-nfs
                mountPath: "/shared"
            securityContext:
              runAsUser: 1000
            env:
            - name: SHARED_DIR
              value: "/shared/comm_${JOB_INDEX}_"
            - name: RANKS
              value: "2"
            resources:
              requests:
                cpu: 1
                memory: 2Gi
              limits:
                cpu: 1
                memory: 2Gi
    Worker:
      replicas: 2
      template:
        spec:
          volumes:
          - name: my-pvc-nfs
            persistentVolumeClaim:
              claimName: nfs
          containers:
          - image: linusseelinger/model-exahype-tsunami:latest
            name: mpi-worker
            volumeMounts:
              # name must match the volume name below
              - name: my-pvc-nfs
                mountPath: "/shared"
            securityContext:
              runAsUser: 1000
            env:
            - name: SHARED_DIR
              value: "/shared/comm_${JOB_INDEX}_"
            command:
            - /usr/sbin/sshd
            args:
            - -De
            - -f
            - /home/mpiuser/.sshd_config
            readinessProbe:
              tcpSocket:
                port: 22
              initialDelaySeconds: 2
            resources:
              requests:
                cpu: 12
                memory: 30Gi
              limits:
                cpu: 12
                memory: 30Gi
